services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: newsDb
      DB_USERNAME: root
      DB_PASSWORD: secretnewsDb
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: newsDb
      MYSQL_PASSWORD: secretnewsDb
      MYSQL_ROOT_PASSWORD: secretnewsDb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
